version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - deploy:
        name: Deploy to host if branch is master
        command: |
        if [ "${CIRCLE_BRANCH}" == "master" ]; then
          apt-get update
          apt-get -qq install git-ftp
          echo "'_$(git status -uno --porcelain | wc -l)_'"
          git status -uno --porcelain
          echo "Initiating Push site:labs.kosmik.id."
          git ftp init --user "${ftp_user_id}" --passwd "${ftp_pass}" ftp://ftp.atchyutn.com
        else
          echo "Not master branch so not deploying"
        fi