version: 2
jobs:
  build:
    docker:
      - image: samueldebruyn/debian-git  
    steps:
      - checkout
      - deploy:
          name: Deploy to host if branch is master
          command: |
            if [ "${CIRCLE_BRANCH}" == "auto-deploy" ]; then
              apt-get update
              apt-get -qq install git-ftp
              echo "'_$(git status -uno --porcelain | wc -l)_'"
              git status -uno --porcelain
              echo "Initiating Push site:atchyutn"
              git ftp init --user "u223156778" --passwd "bhavadev_1" ftp://ftp.atchyutn.com
            else
              echo "Not master branch so not deploying"
            fi   